import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class GildedRose {
    // Create Map of items with name of item as key.
    private Map<String, Item> items;

    public GildedRose(Map<String, Item> items) {
        this.items = items;
    }

    /**
     * Method to apply end of Day updates on collection of Items
     *
     * @return
     */
    public Map endOfDayUpdate() {
        // find generic items first and apply update rules/
        List<String> itemNames = items.keySet().stream().filter
                (
                        key -> !key.equals("Sulfuras") && !key.equals("Aged Brie") && !key.equals("Backstage passes")
                ).collect(Collectors.toList());

        itemNames.forEach(itemName -> {
            Item i = items.get(itemNames);
            i.setSellIn(i.getSellIn() - 1);
            if (i.getSellIn() > 0 && i.getQuality() > 0)
                i.setQuality(i.getQuality() - 1);
            else if (i.getSellIn() < 0 && i.getQuality() > 0)
                i.setQuality(i.getQuality() - 2);
            items.put(itemName, i);
        });

        Arrays.asList("Conjured", "Aged Brie", "Sulfuras", "Backstage passes").forEach(itemName ->
        {
            Item i = items.get(itemName);
            if (!itemName.equals("Sulfuras"))
                i.setSellIn(i.getSellIn() - 1);
            if (itemName.equals(("Conjured"))) {
                if (i.getQuality() > 1)
                    i.setQuality(i.getQuality() - 2);
            }
            if (itemName.equals("Aged Brie")) {
                if (i.getQuality() < 50)
                    i.setQuality(i.getQuality() + 1);
            }
            if (itemName.equals("BackStage Passes")) {
                i = endOfDayBackStagePass(i);
            }
            items.put(itemName, i);
        });
        return this.items;
    }


    private Item endOfDayBackStagePass(Item i) {
        if (i.getSellIn() < 11) {
            if (i.getQuality() + 2 <= 50)
                i.setQuality(i.getQuality() + 2);
            else
                i.setQuality(50);
        }
        if (i.getSellIn() < 6) {
            if (i.getQuality() + 3 <= 50)
                i.setQuality(i.getQuality() + 2);
            else
                i.setQuality(50);
        }
        if (i.getSellIn() <= 0) {
            i.setQuality(0);
        }
        return i;
    }
}



