/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import jdk.management.cmm.SystemResourcePressureMXBean;
import org.junit.Test;
import static org.junit.Assert.*;

import java.util.HashMap;
import java.util.Map;

public class GildedRoseTest {
    @Test public void testSomeLibraryMethod() {
        Map<String,Item> items = new HashMap<String,Item>();
        items.put("+5 Dexterity Vest",new Item(10, 20)); //
        items.put("Aged Brie", new Item(2, 0));
        items.put("Elixir of the Mongoose", new Item(5, 7));
        items.put("Sulfuras",new Item( 0, 80));
        items.put("Sulfuras",new Item( -1, 80));
        items.put("Backstage Passes",new Item( 15, 20));
        items.put("Backstage Passes",new Item(10, 49));
        items.put("Backstage Passes", new Item(5, 49));
                // this conjured item does not work properly yet
        items.put("Conjured", new Item(3, 6));

        GildedRose test = new GildedRose(items);
        System.out.println(test.endOfDayUpdate());
    }
}
